title: Mikhail Tolstov
# logo: tmv.jpg
description: Power Systems Engineer & Machine Learning Engineer
url: "https://https://github.com/TMV1982" # Replace with your actual GitHub Pages URL
theme: jekyll-theme-hacker
